default:
  db: "luca"
  db_host: "localhost"
  db_port: "5432"
  db_user: "postgres"
  db_password: "Sicher!2"
  
test:
  db: "luca"
  db_host: "localhost"
  db_port: "5432"
  db_user: "postgres"
  db_password: "Sicher!2"

production:
  db: "luca"
  db_host: "localhost"
  db_port: "5432"
  db_user: "postgres"
  db_password: "Sicher!2"
