default:
  db: "newdb"
  db_host: "localhost"
  db_port: "5432"
  db_user: "postgres"
  db_password: "admin"
  
test:
  db: "newdb"
  db_host: "localhost"
  db_port: "5432"
  db_user: "postgres"
  db_password: "admin"

production:
  db: "newdb"
  db_host: "localhost"
  db_port: "5432"
  db_user: "postgres"
  db_password: "admin"
