name: Build and Publish Docker Image CI

on:
  release:
    types:
      - published
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - 
        name: Check out
        uses: actions/checkout@v2
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            name/app
            ghcr.io/username/app
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - 
        name: Build Docker image
        run: docker build . --file Dockerfile --tag test_image_name --label "runnumber=${GITHUB_RUN_ID}"
      - 
        name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - 
        name: Push Docker image
        run: |
          docker tag ${{ steps.meta.outputs.tags }}
          docker push $IMAGE_ID:$VERSION
          